"""
GENERATED BY AI TO CHECK DISCREPANCY ISSUES.
Environment and reproducibility check.

Run this on both machines and compare the output. It does two things:

1. Prints every piece of the software environment that could plausibly cause
   small numerical differences between machines (Python, XGBoost, NumPy,
   scikit-learn versions, OS, CPU thread count, default integer size).

2. Re-runs the three locked model configs (Model A, Model B conflict-only,
   Model B all-text) with their exact tuned hyperparameters and compares the
   result against the values recorded in sudan_results.csv, flagging any
   config where the two don't match within a small tolerance.

Usage:
    python check_reproducibility.py
"""

import platform
import sys

import numpy as np
import pandas as pd
import sklearn
import xgboost

from models.train_models import train_evaluate_model
from utils.data_prep import get_clean_combined_data

# ============================================================
# Part 1: Environment fingerprint
# ============================================================


def print_environment_info():
    print("=" * 60)
    print("ENVIRONMENT")
    print("=" * 60)
    print(f"Python version:      {sys.version}")
    print(f"Platform:            {platform.platform()}")
    print(f"Processor:           {platform.processor()}")
    print(f"CPU count:           {import_os_cpu_count()}")
    print(f"NumPy version:       {np.__version__}")
    print(f"NumPy default int:   {np.array([1]).dtype}")
    print(f"Pandas version:      {pd.__version__}")
    print(f"scikit-learn version:{sklearn.__version__}")
    print(f"XGBoost version:     {xgboost.__version__}")
    print()
    print("Compare every line above against the other machine's output.")
    print("Any difference is a plausible explanation for small result drift.")
    print()


def import_os_cpu_count():
    import os

    return os.cpu_count()


# ============================================================
# Part 2: Reproducibility check against locked results
# ============================================================

# Config, tuned hyperparameters, and the values recorded in sudan_results.csv
# for each. Update the "expected" values here if the locked results ever
# change - this file should always reflect whatever you're treating as final.
LOCKED_MODELS = {
    "Model A": {
        "config": {
            "include_food": True,
            "include_rain": True,
            "include_text": False,
            "conflict_only": None,
            "k": 1.75,
            "event_col": "sub_event_type",
            "n_splits": 5,
            "use_pca": False,
        },
        "params": {
            "max_depth": 3,
            "min_child_weight": 1,
            "max_delta_step": 0,
            "gamma": 0,
            "learning_rate": 0.01,
            "subsample": 0.6,
            "colsample_bytree": 0.8,
            "reg_alpha": 2.0,
            "reg_lambda": 1,
            "colsample_bylevel": 1.0,
        },
        "expected_onset_aupr": 0.3336,
        "expected_active_aupr": 0.2025,
    },
    "Model B (conflict-only text)": {
        "config": {
            "include_food": True,
            "include_rain": True,
            "include_text": True,
            "conflict_only": True,
            "k": 1.75,
            "event_col": "sub_event_type",
            "n_splits": 5,
            "use_pca": True,
        },
        "params": {
            "max_depth": 7,
            "min_child_weight": 1,
            "max_delta_step": 0,
            "gamma": 3,
            "learning_rate": 0.01,
            "subsample": 1.0,
            "colsample_bytree": 1.0,
            "reg_alpha": 2.0,
            "reg_lambda": 10,
            "colsample_bylevel": 0.8,
        },
        "expected_onset_aupr": 0.3941,
        "expected_active_aupr": 0.2155,
    },
    "Model B (all-event text)": {
        "config": {
            "include_food": True,
            "include_rain": True,
            "include_text": True,
            "conflict_only": False,
            "k": 1.75,
            "event_col": "sub_event_type",
            "n_splits": 5,
            "use_pca": True,
        },
        "params": {
            "max_depth": 5,
            "min_child_weight": 1,
            "max_delta_step": 1,
            "gamma": 5,
            "learning_rate": 0.01,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "reg_alpha": 2.0,
            "reg_lambda": 10,
            "colsample_bylevel": 1.0,
        },
        "expected_onset_aupr": 0.3127,
        "expected_active_aupr": 0.2262,
    },
}

TOLERANCE = 0.005  # AUPR difference beyond this is flagged as a real mismatch


def run_locked_model(config, params):
    """Minimal, standalone version of run_model - no notebook dependencies."""
    data_sources = [
        src
        for src, include in zip(
            ["food", "rain", "text"],
            [config["include_food"], config["include_rain"], config["include_text"]],
        )
        if include
    ]

    model_data, predictor_cols = get_clean_combined_data(
        data_sources=data_sources,
        k=config["k"],
        event_col=config["event_col"],
        conflict_only_embeddings=config["conflict_only"],
    )

    final_params = {
        **params,
        "k": config["k"],
        "event_col": config["event_col"],
        "n_splits": config["n_splits"],
        "use_pca": config["use_pca"],
    }

    results, _, _, _ = train_evaluate_model(
        model_data,
        predictor_cols,
        final_params,
        best_params=True,
        use_pca=config["use_pca"],
        compute_shap=False,
        return_onset_predictions=False,
    )
    return results


def check_reproducibility():
    print("=" * 60)
    print("REPRODUCIBILITY CHECK")
    print("=" * 60)

    any_mismatch = False

    for label, spec in LOCKED_MODELS.items():
        print(f"\nRunning: {label}...")
        results = run_locked_model(spec["config"], spec["params"])

        actual_onset = float(results["onset_aupr"])
        actual_active = float(results["active_aupr"])
        expected_onset = spec["expected_onset_aupr"]
        expected_active = spec["expected_active_aupr"]

        onset_diff = actual_onset - expected_onset
        active_diff = actual_active - expected_active

        onset_status = "OK" if abs(onset_diff) <= TOLERANCE else "MISMATCH"
        active_status = "OK" if abs(active_diff) <= TOLERANCE else "MISMATCH"

        if onset_status == "MISMATCH" or active_status == "MISMATCH":
            any_mismatch = True

        print(f"  {label}")
        print(
            f"    onset_aupr:  expected={expected_onset:.4f}  actual={actual_onset:.4f}  "
            f"diff={onset_diff:+.4f}  [{onset_status}]"
        )
        print(
            f"    active_aupr: expected={expected_active:.4f}  actual={actual_active:.4f}  "
            f"diff={active_diff:+.4f}  [{active_status}]"
        )

    print()
    print("=" * 60)
    if any_mismatch:
        print(
            "RESULT: One or more models did not reproduce within tolerance "
            f"({TOLERANCE}). Compare the environment fingerprint above against "
            "the other machine's output to look for a version difference."
        )
    else:
        print(
            "RESULT: All models reproduced within tolerance. This machine is consistent."
        )
    print("=" * 60)


if __name__ == "__main__":
    print_environment_info()
    check_reproducibility()
